#include <stdio.h>
#include <time.h>
#include <stdlib.h>
#include <unistd.h>
#include "slidegame.h"

#define COLUMNS 4
#define ROWS 4

//clears screen by moving display down (from lecture)
void clearScreen(){
    printf("\e[2J\e[H");
}

//prints MindPuzzle logo
void startGame(){
    printf("\033[1;36m");
    printf("=========================================================\n");
    printf("\033[0m");
    
    
    printf("\033[01;33m");

    printf("      __  ____           ______                  __   \n");
    printf("     /  |/  (_)___  ____/ / __ \\__  __________  / /__ \n");
    printf("    / /|_/ / / __ \\/ __  / /_/ / / / /_  /_  / / / _ \\\n");
    printf("   / /  / / / / / / /_/ / ____/ /_/ / / /_/ /_/ /  __/\n");
    printf("  /_/  /_/_/_/ /_/\\__,_/_/    \\__,_/ /___/___/_/\\___/\n\n"); 




    printf("\033[0m");
    printf("\033[1;36m");
    printf("===============================Aidan Arianna Eric========\n");
    printf("\033[0m");

}

//clears screen prints border and board and puts a blank spot where zero is 
void printBoard(int gameArray[ROWS][COLUMNS]){ //solid border
    int yCord, xCord;
    clearScreen();
    startGame();                        
    printf("\033[1;31m                   ¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦\n \033[0m");
    printf("\033[1;31m                  ¦                   ¦\033[0m");
    for(yCord=0; yCord<4; yCord++){
        printf("\n                   ");
        printf("\033[1;31m¦\033[0m");
        for(xCord=0; xCord<4; xCord++){
            if (gameArray[yCord][xCord]!=0){
                printf("%4d", gameArray[yCord][xCord]);
            }
            else{ 
                printf("    ");
            }
        }
        printf("\033[1;31m   ¦\033[0m");
    }
    printf("\033[1;31m\n                   ¦                   ¦\n \033[0m");
    printf("\033[1;31m                  ¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦\033[0m");
}
 

//used to fill array with -1
//this is useful because the random array is generated by checking if a random value already appears in the array.
void popArray(int gameArray[COLUMNS][ROWS]){
    int x, y;
    for(y=0; y<COLUMNS; y++){
        for(x=0; x<ROWS; x++){
            gameArray[x][y]=-1;
        }
    }
}

//used to check if a number is inside array, if not we can add that number to the array
int checkArray(int gameArray[COLUMNS][ROWS], int check){
    int x, y;
    for(y=0; y<COLUMNS; y++){
        for(x=0; x<ROWS; x++){
            if(gameArray[y][x]==check){
            return 1;
            }
        }
    }
    return 0;
}
//used to create random array
void randArray(int gameArray[COLUMNS][ROWS]){
    int x, y, temp;
    popArray(gameArray);
    for(y=0; y<COLUMNS; y++){
        for(x=0; x<ROWS; x++){ //assigns unique random numbers to each spot in array
            do{
                temp=rand()%16; //temp is set to a random number
            }while(checkArray(gameArray, temp)==1); //if number is already used, it will go back until # is unique
            gameArray[y][x]=temp; //adds temp to array
        }
    }
    if (endGame(gameArray)==1 || solveCheck(gameArray)==0 ){ //checks for winning board and solvability
    randArray(gameArray);
    }
}

//checks to for solvability
//based off proof from powerpoint
int solveCheck(int gameArray[COLUMNS][ROWS]){
    int x, y; //used to cycle through the array
    int xTemp, yTemp; //used to count instances of inversion following each value *see algorithm linked in references*
    int instances=0; //running total of instances
    int rowNot; //the row of the zero spot
    
    // finding row not
    for(y=0; y<ROWS; y++){
        for(x=0; x<COLUMNS; x++){
            if (gameArray[y][x]==0){
                    rowNot = y;
            }
        }
    }
    //calculating instances of inversion 
    for(y=0; y<COLUMNS; y++){
        for(x=0; x<ROWS; x++){
            yTemp=y;
            xTemp=x;
            while(yTemp<COLUMNS){
                while(xTemp<ROWS){
                    if(gameArray[y][x] > gameArray[yTemp][xTemp] && gameArray[yTemp][xTemp] != 0){
                        instances+=1;
                    }
                    xTemp++;
                }
            xTemp=0; //makes sure we check all values in next row
            yTemp++; 
            }
        }
    }
    printf("instances= %d, rowNot= %d\n", instances, rowNot);
    //check for opposite parity (odd/even)
    if(instances%2==rowNot%2){
    return 0; //unsolvable 
    }
    else{
    return 1; //solvable 
    }
}
            
                        
                    

//Checks current array against winning array, ends game if match
int endGame(int gameArray[ROWS][COLUMNS]) {
    int endArray[ROWS][COLUMNS] = {{1,2,3,4}, //this is the winnning array
                                 {5,6,7,8},
                                 {9,10,11,12},
                                 {13,14,15,0}};
    int x = 0, y = 0; //used to index the gameArray
    for(y = 0; y < ROWS; y++) {
        for (x = 0; x < COLUMNS; x++) {
            if (gameArray[y][x] != endArray[y][x]) {
                return 0; //return 0 as soon as there is a difference in arrays
            }
        }
    }
    return 1; //if no differences return a 1 and they win!
}



//finds where the zero spot is on an empty board
void findNot(int gameArray[ROWS][COLUMNS], int *xNot, int *yNot){ //uses pointers to define xNot and yNot in main
    int y, x;
    for(y=0; y<ROWS; y++){
        for(x=0; x<COLUMNS; x++){
            if (gameArray[y][x]==0){
                *xNot = x;
                *yNot = y;
            }
        }
    }
}

//reads in a user input and returns a corresponding number
int userInput(int gameArray[COLUMNS][ROWS]) {
    char input; //stores input character
    do {
        printBoard(gameArray); //prints board and logo
        printf("\n                Enter command (a,s,d,w): \n"); //prints instructions
        printf("           w = up,a = left,s = down,d = right \n"); //prints instructions
        scanf(" %c",&input); // scans input and ignores whitespace
    } while ((input != 'a') && (input != 's') && (input != 'd') && (input != 'w')); //only scans wasd and ignores rest
    switch (input) {
        case 'w':
            return 1;
            break;
        case 'a':
            return 2;
            break;
        case 's':
            return 3;
            break;
        case 'd':
            return 4;
            break;
        default:
            return 0;
    }
}

//prints gameover in yellow
void gameOver(){ //prints game over
    clearScreen();
    printf("\n\n\n\n\n");
    printf("\033[01;33m"); // does coloring
    printf("      _______   ________  ___ __ __  ______       ______  __   __  ______  ______       \n");
    printf("     /______/\\ /_______/\\/__//_//_/\\/_____/\\     /_____/\\/_/\\ /_/\\/_____/\\/_____/\\      \n");
    printf("     \\::::__\\/_\\::: _  \\ \\::\\| \\| \\ \\::::_\\/_    \\:::_ \\ \\:\\ \\\\ \\ \\::::_\\/\\:::_ \\ \\     \n");
    printf("      \\:\\ /____/\\::(_)  \\ \\:.      \\ \\:\\/___/\\    \\:\\ \\ \\ \\:\\ \\\\ \\ \\:\\/___/\\:(_) ) )_   \n");
    printf("       \\:\\\\_  _\\/\\:: __  \\ \\:.\\-/\\  \\ \\::___\\/_    \\:\\ \\ \\ \\:\\_/.:\\ \\::___\\/\\: __ `\\ \\  \n");
    printf("        \\:\\_\\ \\ \\ \\:.\\ \\  \\ \\. \\  \\  \\ \\:\\____/\\    \\:\\_\\ \\ \\ ..::/ /\\:\\____/\\ \\ `\\ \\ \\ \n");
    printf("         \\_____\\/  \\__\\/\\__\\/\\__\\/ \\__\\/\\_____\\/     \\_____\\/\\___/_(  \\_____\\/\\_\\/ \\_\\/ \n");

}
